### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by egernst** [neszt/cppcheck-docker#2]
Hey @neszt - I found this helpful - thanks.

You have a license for this?  I'd like to leverage, but want to make sure I'm in the clear (ie, apache2, or MIT, or... )?

**Comment by neszt** [comment]
Feel free to use any snippets from the Dockerfile.

A container image (a file system that may include various copyrighted works) and the scripts to build these images (like a Dockerfile) are separate works. In general, the license of the included software is completely unrelated to the license of the build scripts.
