### ISSUE TITLE
Tag docker image

### ISSUE THREAD

**Issue by mahoyen** [neszt/cppcheck-docker#4]
Could you please add a tag other than `latest` to your docker images? 

This way the dependency is not broken if you change something in the future.

Thanks!

**Comment by neszt** [comment]
I'm glad you asked!

I made it possible to compile any version: https://github.com/neszt/cppcheck-docker/commit/be787561e1fc7c364fe2a9d80dcd1873d3773d2a

In addition, tagged version 2.2 is now available: https://hub.docker.com/r/neszt/cppcheck-docker/tags

**Comment by mahoyen** [comment]
Thanks!
